workflowVersion: 1.0.0
sources:
    merge-code-samples-into-spec:
        inputs:
            - location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/my-source
        overlays:
            - location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/code-samples-go-speakeasy-client-sdk-go:main
            - location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/code-samples-java-java-target:main
        output: ./openapi.yaml
targets: {}
